services:
  - type: web
    name: telegram-redirect-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
